# Generated by Django 2.2 on 2021-10-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateOfAnalysis',
            fields=[
                ('certificate_of_analsys_id', models.IntegerField(db_column='CERTIFICATE_OF_ANALSYS_ID', primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(blank=True, db_column='INVOICE_NO', max_length=500, null=True)),
                ('batch', models.CharField(blank=True, db_column='BATCH', max_length=500, null=True)),
                ('quantity', models.CharField(blank=True, db_column='QUANTITY', max_length=500, null=True)),
                ('expiry_date', models.CharField(blank=True, db_column='EXPIRY_DATE', max_length=255, null=True)),
                ('doc_path', models.CharField(db_column='DOC_PATH', max_length=500)),
                ('created_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('edited_on', models.DateTimeField(blank=True, null=True)),
                ('edited_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'COA',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.IntegerField(db_column='INVOICE_ID', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=500, null=True)),
                ('material_name', models.TextField(blank=True, db_column='MATERIAL_NAME', null=True)),
                ('quantity', models.CharField(blank=True, db_column='QUANTITY', max_length=500, null=True)),
                ('unit', models.CharField(blank=True, db_column='UNIT', max_length=500, null=True)),
                ('invoice_no', models.CharField(blank=True, db_column='INVOICE_NO', max_length=500, null=True)),
                ('invoice_date', models.CharField(blank=True, db_column='INVOICE_DATE', max_length=500, null=True)),
                ('po_number', models.CharField(blank=True, db_column='PO_NUMBER', max_length=500, null=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=500, null=True)),
                ('hsn', models.CharField(blank=True, db_column='HSN', max_length=500, null=True)),
                ('amount', models.CharField(blank=True, db_column='AMOUNT', max_length=500, null=True)),
                ('batch', models.CharField(blank=True, db_column='BATCH', max_length=500, null=True)),
                ('bill_of_entry_no', models.CharField(blank=True, db_column='BILL_OF_ENTRY_NO', max_length=500, null=True)),
                ('grn', models.CharField(blank=True, db_column='GRN', max_length=500, null=True)),
                ('invoice_path', models.TextField(blank=True, db_column='INVOICE_PATH', null=True)),
                ('created_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('edited_on', models.DateTimeField(blank=True, null=True)),
                ('edited_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'INVOICE',
            },
        ),
    ]
