# Generated by Django 2.2 on 2021-11-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateofanalysis',
            name='certificate_of_analsys_id',
            field=models.AutoField(db_column='CERTIFICATE_OF_ANALSYS_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.AutoField(db_column='INVOICE_ID', primary_key=True, serialize=False),
        ),
    ]
