# Generated by Django 2.2 on 2021-11-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_auto_20211114_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateofanalysis',
            name='doc_path',
            field=models.CharField(blank=True, db_column='DOC_PATH', max_length=500, null=True),
        ),
    ]
