# Generated by Django 2.2 on 2021-11-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0003_auto_20211114_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_of_ladding',
            field=models.TextField(blank=True, db_column='BILL_OFF_LADDING', null=True),
        ),
    ]
