# Generated by Django 2.2 on 2021-11-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0004_invoice_bill_of_ladding'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateofanalysis',
            name='coa_text',
            field=models.CharField(blank=True, db_column='COA_TEXT', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='certificateofanalysis',
            name='date_of_manfacture',
            field=models.CharField(blank=True, db_column='DATE_OF_MANFACTURE', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='certificateofanalysis',
            name='unit',
            field=models.CharField(blank=True, db_column='UNIT', max_length=500, null=True),
        ),
    ]
