# Generated by Django 2.2 on 2021-12-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0005_auto_20211118_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='document_po_number',
            field=models.CharField(blank=True, db_column='DOCUMENT_PO_NUMBER', max_length=500, null=True),
        ),
    ]
