# Generated by Django 2.2 on 2021-12-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0006_invoice_document_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateofanalysis',
            name='deleted_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
