# Generated by Django 2.2 on 2021-12-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0007_certificateofanalysis_deleted_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateofanalysis',
            name='deleted_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
