# Generated by Django 2.2 on 2021-12-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0008_auto_20211206_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateofanalysis',
            name='po_number',
            field=models.CharField(blank=True, db_column='PO_NUMBER', max_length=500, null=True),
        ),
    ]
