# Generated by Django 2.2 on 2022-01-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0011_invoice_boe_doc_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sender_email',
            field=models.CharField(blank=True, db_column='SENDER_EMAIL', max_length=500, null=True),
        ),
    ]
