# Generated by Django 2.2 on 2022-03-15 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0014_auto_20220106_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='hsn',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='material_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='unit',
        ),
        migrations.CreateModel(
            name='InvoiceTableData',
            fields=[
                ('invoice_table_data_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('material_name', models.TextField(blank=True, db_column='MATERIAL_NAME', null=True)),
                ('quantity', models.CharField(blank=True, db_column='QUANTITY', max_length=500, null=True)),
                ('unit', models.CharField(blank=True, db_column='UNIT', max_length=500, null=True)),
                ('hsn', models.CharField(blank=True, db_column='HSN', max_length=500, null=True)),
                ('amount', models.CharField(blank=True, db_column='AMOUNT', max_length=500, null=True)),
                ('batch_no', models.CharField(blank=True, db_column='BATCH_NO', max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now=True, null=True)),
                ('edited_on', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestApp.Invoice')),
            ],
        ),
    ]
