# Generated by Django 2.2 on 2022-03-15 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0015_auto_20220315_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateFormatRegexTemplate',
            fields=[
                ('date_format_regex_template_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('template', models.CharField(blank=True, max_length=1000, null=True)),
                ('reated_on', models.DateTimeField(auto_now=True)),
                ('edited_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFields',
            fields=[
                ('document_field_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(blank=True, max_length=200, null=True)),
                ('field_type', models.CharField(blank=True, choices=[('SINGLE', 'SINGLE'), ('MULTIPLE', 'MULTIPLE')], max_length=100, null=True)),
                ('date_field', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('edited_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTypes',
            fields=[
                ('document_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(blank=True, max_length=150, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('edited_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegexTemplates',
            fields=[
                ('regex_template_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('template', models.CharField(blank=True, max_length=1000, null=True)),
                ('reated_on', models.DateTimeField(auto_now=True)),
                ('edited_on', models.DateTimeField(blank=True, null=True)),
                ('document_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestApp.DocumentFields')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestApp.DocumentTypes')),
            ],
        ),
        migrations.CreateModel(
            name='FieldIdentifiers',
            fields=[
                ('field_identifier_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('edited_on', models.DateTimeField(blank=True, null=True)),
                ('document_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestApp.DocumentFields')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestApp.DocumentTypes')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentIdentifier',
            fields=[
                ('documnet_identifier_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identifier_keyword', models.CharField(blank=True, max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('edited_on', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestApp.DocumentTypes')),
            ],
        ),
        migrations.AddField(
            model_name='documentfields',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestApp.DocumentTypes'),
        ),
    ]
